version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: toucans_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1234@127.0.0.1:5432/toucans_hub
    ports:
      - "8000:8000"

volumes:
  postgres_data:
