"""Added username to promptfunction

Revision ID: 6664bf4fc765
Revises: eea492e9ad8b
Create Date: 2023-12-03 22:49:04.204805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6664bf4fc765'
down_revision: Union[str, None] = 'eea492e9ad8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promptfunction', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_promptfunction_username'), 'promptfunction', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promptfunction_username'), table_name='promptfunction')
    op.drop_column('promptfunction', 'username')
    # ### end Alembic commands ###
