"""Changed chat_api_config to completion_config

Revision ID: 791a3d90ee28
Revises: e30d824cff17
Create Date: 2023-12-09 15:52:52.358823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '791a3d90ee28'
down_revision: Union[str, None] = 'e30d824cff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promptfunction', sa.Column('completion_config', sa.JSON(), nullable=True))
    op.drop_column('promptfunction', 'chat_api_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promptfunction', sa.Column('chat_api_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('promptfunction', 'completion_config')
    # ### end Alembic commands ###
