"""removed username

Revision ID: e30d824cff17
Revises: 3e27955dec0a
Create Date: 2023-12-04 07:50:55.123703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e30d824cff17'
down_revision: Union[str, None] = '3e27955dec0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promptfunction_username', table_name='promptfunction')
    op.drop_column('promptfunction', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promptfunction', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_promptfunction_username', 'promptfunction', ['username'], unique=False)
    # ### end Alembic commands ###
